# Generated by Django 3.2.6 on 2021-08-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='password2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.TextField(),
        ),
    ]
